Initial release of python client library
LexMachinaInc/python-lexmachina-api-client pull request #2
Opened 2022-10-03 19:14 UTC by rmblau

This is the first version of the python client library. It has 100% coverage of the API. it also includes tests for each function.

2022-10-03 20:22 UTC, mel-seto requested changes
Took an initial glance and noticed some test names could be improved

2022-10-03 20:22 UTC, mel-seto commented on src/tests/test_health.py
> +    async def test_get_patents_integer_fuzz(self):
doesn't seem like an appropriate class name or test name

2022-10-03 20:22 UTC, mel-seto commented on src/tests/test_list_damages.py
> +        response = await self.client.list_damages()
test_list_damages would be more relevant test name

2022-10-03 20:25 UTC, rmblau commented on src/tests/test_list_damages.py
> +        response = await self.client.list_damages()
@mel-seto changes have been made to address this and your previous comment :)

2022-10-04 14:22 UTC, mel-seto requested changes

2022-10-04 14:22 UTC, mel-seto commented on src/lexmachina/auth.py
> +            else:
I wonder if you could improve the readability of this module by implementing one of these suggestions: https://stackoverflow.com/questions/60208/replacements-for-switch-statement-in-python

2022-10-04 14:22 UTC, mel-seto commented on src/lexmachina/client.py
> +            response = await self.get(path='parties', args=parties)
`else` statements following a `return` are superfluous IMO

2022-10-04 14:22 UTC, mel-seto commented on src/lexmachina/client.py
> +        return response
Could you do `return await self.list(path='list-case-resolutions')`?

2022-10-04 14:22 UTC, mel-seto commented on src/tests/pytest.ini
> +asyncio_mode = auto
I don't remember where i've seen `asyncio` before but good find

2022-10-04 14:22 UTC, mel-seto commented on src/tests/test_get_judges.py
> +    @pytest.mark.parametrize("federal_judges", [0, -2, 999999999])
Because we are reusing the same "integer fuzz" across classes and tests, we should extract a constant `INTEGER_FUZZ` and add it to the `__init__` file

2022-10-04 14:22 UTC, mel-seto commented on src/tests/test_list_courts.py
> +        assert any(i['type'] == 'FederalDistrict' for i in response)
The use of `i` is not very pythonic, perhaps use a more descriptive variable name

2022-10-04 14:22 UTC, mel-seto commented on src/tests/test_list_events.py
> +    async def test_get_events(self):
I would rename all the `list` tests to use the word `list` instead of `get`

2022-10-04 14:22 UTC, mel-seto commented on src/lexmachina/client.py
> +        return response
(apply same comment to similar tests)

2022-10-04 14:34 UTC, rmblau commented on src/lexmachina/client.py
> +            response = await self.get(path='parties', args=parties)
I realized that I can just return response once, am changing everything to use this.

2022-10-04 14:37 UTC, rmblau commented on src/lexmachina/client.py
> +        return response
changing all list endpoints to use this pattern

2022-10-04 14:40 UTC, rmblau commented on src/lexmachina/auth.py
> +            else:
the match/case statement is tied to python 3.10 and I didn't necessarily want to tie this sdk to a version higher than what we use internally and make it where external users will have to be using 3.10+ where their existing codebase could be in 3.8-3.9. In the future when 3.9 hits EOL I would investigate into the use of the match case, but for now I do not want to tie it to 3.10. Other than match/case I would be interested to see how you would maybe re-write the if/else chain?

2022-10-04 14:49 UTC, rmblau commented on src/tests/test_list_courts.py
> +        assert any(i['type'] == 'FederalDistrict' for i in response)
Changed to be more specific to the test

2022-10-04 14:50 UTC, rmblau commented on src/tests/test_list_events.py
> +    async def test_get_events(self):
changed

2022-10-04 15:12 UTC, rmblau commented on src/tests/test_get_judges.py
> +    @pytest.mark.parametrize("federal_judges", [0, -2, 999999999])
latest changes address this.

2022-10-05 21:06 UTC, rmblau commented
All tests pass, have made some changes to the file structure. As such, am merging this PR.

2022-10-05 21:06 UTC, merged